sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: project_description
        field:
          antlers: false
          display: 'Project Description'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: project_logo
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Project Logo'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: project_link_label
        field:
          input_type: text
          antlers: false
          display: 'Project Link Label'
          type: text
          icon: text
          width: 50
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: project_link_url
        field:
          display: 'Project Link URL'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          width: 50
title: Project
